language: perl
perl:
  - "blead"
  - "dev"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10.1"
  - "5.10.0"

matrix:
  include:
      env: COVERAGE=1
  allow_failures:
    - perl: "blead"

sudo: false

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
