language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "dev"
#  - "blead" https://github.com/travis-perl/helpers/issues/44
sudo: required

services:
  - docker

env:
  global:
    - EXA_URI=db:exasol://sys:exasol@127.0.0.1:8888/?Driver=Exasol
    - VSQL_URI=db:vertica://dbadmin@localhost:5433/docker?Driver=Vertica

matrix:
  include:
    - perl: "5.26"
      env: COVERAGE=1
  allow_failures:
    - perl: "blead"

before_install:
  # Install prepreqs.
  - sudo apt-get update -qq
  - sudo apt-get install -qq gettext aspell-en unixodbc-dev odbcinst unixodbc
  - cat t/odbc/odbcinst.ini | sudo tee -a /etc/odbcinst.ini

  # Set up Firebird.
  - sudo apt-get install -qq firebird2.5-superclassic firebird2.5-dev
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
  - sudo service firebird2.5-superclassic start

  # Set up Vertica.
  - cat t/odbc/vertica.ini | sudo tee -a /etc/vertica.ini
  - docker pull cjonesy/docker-vertica:latest
  - docker run -d -p 5433:5433 --rm sumitchawla/vertica
  - docker ps -a
  - curl -O https://my.vertica.com/client_drivers/8.1.x/8.1.1-7/vertica-client-8.1.1-7.x86_64.tar.gz
  - sudo tar -xzf vertica-client-8.1.1-7.x86_64.tar.gz -C /
  - export PATH=/opt/vertica/bin:$PATH

  # Set up Exasol.
  - docker pull exasol/docker-db:latest
  - docker run -d -p 127.0.0.1:8888:8888 --privileged --rm exasol/docker-db:latest
  - docker ps -a
  - curl -O https://www.exasol.com/support/secure/attachment/55217/EXASOL_ODBC-6.0.4.tar.gz
  - sudo tar -xvzf EXASOL_ODBC-6.0.4.tar.gz -C /opt
  - curl -O https://www.exasol.com/support/secure/attachment/55310/EXAplus-6.0.4.tar.gz
  - sudo tar -xzf EXAplus-6.0.4.tar.gz -C /opt
  - export PATH=/opt/EXAplus-6.0.4:$PATH

  # Set up Perl.
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpanm --verbose --no-interactive --no-man-pages --notest Params::Validate DBI File::Which Test::More Test::Exception Time::HiRes Template
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup
  - vsql -U dbadmin -d docker -c 'SELECT VERSION();'
  - exaplus -c 127.0.0.1:8888 -u sys -p exasol -sql "SELECT current_timestamp;"
  # - perl -e "use DBI; use DBD::ODBC; my \$conn = DBI->connect('dbi:ODBC:EXAHOST=127.0.0.1;EXAPORT=8888;Driver=Exasol','sys','exasol'); print \$conn->selectcol_arrayref('SELECT current_timestamp')->[0];"
  # - ldd -r $(grep libexaodbc /etc/odbcinst.ini|awk '{print $3}')

script:
  - prove -lr --directives $(test-dirs)

after_success:
  - coverage-report

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.net#sqitch"
    on_success: change
    on_failure: always
