# This workflow tests Sqitch's Oracle engine on recent supported versions of
# Oracle. It runs for pushes and pull requests on the `main`, `develop`,
# `**oracle**`, and `**engine**` branches.
name: 🔮 Oracle
on:
  push:
    branches: [main, develop, "**engine**", "**oracle**" ]
  pull_request:
    branches: [main, develop, "**engine**", "**oracle**" ]
jobs:
  Oracle:
    strategy:
      matrix:
        oracle:
          # In 11g, APP_USER "sqitchtest" is created in XE, but in more reent
          # versions it is not. So we use an existing user in those versions.
          # Docker image source: https://github.com/gvenzl/oci-oracle-xe/
          # - { version: 21c, tag: 21-full, service: XE, altUser: gsmuser    }
          - { version: 18c, tag: 18-slim, service: XE, altUser: gsmuser    }
          - { version: 11g, tag: 11-slim, service: XE, altuser: sqitchtest }
    name: "🔮 Oracle ${{ matrix.oracle.version }}"
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-xe:${{ matrix.oracle.tag }}
        ports: [ 1521 ]
        env:
          ORACLE_PASSWORD: oracle
          APP_USER: sqitchtest
          APP_USER_PASSWORD: sqitchtest
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
    steps:
      - run: "echo Filter: ${{ needs.filter.outputs.oracle }}"
      - uses: actions/checkout@v2
      - name: Setup Clients
        run: ./dev/linux-oracle
      - name: Setup Perl
        id: perl
        uses: shogo82148/actions-setup-perl@v1
        with: { perl-version: latest }
      - name: Cache CPAN Modules
        uses: actions/cache@v2
        with:
          path: local/lib
          key: perl-${{ steps.perl.outputs.perl-hash }}
      - name: Download cpanfile
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://fastapi.metacpan.org/source/DWHEELER/App-Sqitch-v1.1.0/dist/cpanfile
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends --cpanfile cpanfile
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends DBD::Oracle
      - name: prove
        env:
          PERL5LIB: "${{ github.workspace }}/local/lib/perl5"
          LIVE_ORACLE_REQUIRED: true
          SQITCH_TEST_ALT_ORACLE_REGISTRY: "${{ matrix.oracle.altUser }}"
          SQITCH_TEST_ORACLE_URI: db:oracle://system:oracle@127.0.0.1:${{ job.services.oracle.ports[1521] }}/${{ matrix.oracle.service }}
        run: prove -lvr t/oracle.t
