# This workflow is intended to be the default to check for compatability across
# operating systems without much overhead. It uses the latest version of Perl on
# the latest versions of Ubunti, macOS, and Windows. Think of it as a quick
# check for working branches.
name: 🅾️ OS
on: [push, pull_request]
jobs:
  OS:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    name: 🅾️ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        id: perl
        uses: shogo82148/actions-setup-perl@v1
        with: { perl-version: latest }
      - run: perl -V
      - name: Cache CPAN Modules
        uses: actions/cache@v2
        with:
          path: local/lib
          key: perl-${{ steps.perl.outputs.perl-hash }}
      - name: Download cpanfile
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://fastapi.metacpan.org/source/DWHEELER/App-Sqitch-v1.1.0/dist/cpanfile
      # Remove Locale::TextDomain if https://github.com/gflohr/libintl-perl/issues/7 fixed and released.
      - if: ${{ matrix.os == 'windows' }}
        run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends Encode Win32::Console::ANSI Win32API::Net Win32::Locale Win32::ShellQuote DateTime::TimeZone::Local::Win32 Locale::TextDomain@1.31
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends --cpanfile cpanfile
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends Test::Spelling Test::Pod Test::Pod::Coverage
      - name: prove
        env: { PERL5LIB: "${{ github.workspace }}/local/lib/perl5" }
        run: prove -lr --comments --directives
