# This workflow tests Sqitch's PostgreSQL engine on all supported versions of
# Postgres. It runs for pushes and pull requests on the main and develop
# branches, or any time a file matching "**pg**" changes.
name: 🐘 Postgres
on:
  push:
    branches: [main, develop]
    paths: ['**pg**', '!**upgrade**']
  pull_request:
    branches: [main, develop]
    paths: ['**pg**', '!**upgrade**']
jobs:
  Postgres:
    strategy:
      matrix:
        pg: [14, 13, 12, 11, 10, 9.6, 9.5, 9.4, 9.3] #, 9.2, 9.1, 9.0, 8.4] https://github.com/bucardo/dbdpg/issues/84
    name: 🐘 Postgres ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - run: pg-start ${{ matrix.pg }}
      - uses: actions/checkout@v2
      - name: Setup perl
        id: perl
        uses: shogo82148/actions-setup-perl@v1
        with: { perl-version: latest }
      - name: Cache CPAN Modules
        uses: actions/cache@v2
        with:
          path: local/lib
          key: perl-${{ steps.perl.outputs.perl-hash }}
      - name: Download cpanfile
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://fastapi.metacpan.org/source/DWHEELER/App-Sqitch-v1.1.0/dist/cpanfile
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends --cpanfile cpanfile
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends DBD::Pg Algorithm::Backoff::Exponential
      - name: prove
        env: { PERL5LIB: "${{ github.workspace }}/local/lib/perl5" }
        run: prove -lvr t/pg.t
